### PR TITLE
Convert tests from QUnit to Mocha 

### PR DESCRIPTION
**Pull request by jvmvik**
Well I have migrate the test to Mocha / chaijs + mocha-phantomjs.
You might need to install mocha-phantomjs as standalone.
$npm install -g mocha-phantomjs

I moved the tests to test/ to follow mocha naming convention.
Also, I have created a script entry for test in the package.json, this enables to run the regression with:
$npm test

I had to modify only a single line of actual test.
I have re-implemented Component test in BDD style.

Let me know if you have any questions.

Link:
https://www.bountysource.com/issues/11170504-convert-tests-from-qunit-to-mocha-teaspoon/developers

### CODE REVIEW

**Comment by sankho** [comment]
Hey man - thanks a bunch; I'm gonna take a look at this over the weekend and put comments in

**Comment by jvmvik** [comment]
Looking forward to your feedbacks..

**Comment by jvmvik** [comment]
Any update on this?

**Comment by armand1m** [comment]
Forgotten?

**Comment by sankho** [comment]
@jvmvik @armand1m apologies, react and bad notifications took over my life. @jvmvik closing out and paying out.

**Pull request merged**
